# Generated by Django 3.2.3 on 2021-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='position',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
