# Generated by Django 3.2.3 on 2021-08-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('badges', '0002_delete_employeebadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('employee_guid', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('giver_guid', models.CharField(max_length=40)),
                ('badge',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='badges.badge')),
            ],
        ),
    ]
