# Generated by Django 3.2.3 on 2021-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_employeebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebadge',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
