# Generated by Django 3.2.3 on 2021-08-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('badges', '0005_groupbadges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='group',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='badges',
                to='badges.groupbadges'
            ),
        ),
    ]
