# Generated by Django 3.2.3 on 2021-08-31 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('badges', '0006_badge_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebadge',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='employeebadge',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='badge',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='badges',
                to='badges.groupbadges'
            ),
        ),
    ]
